                                                                       DEFORESTATION
Deforestation is the permanent destruction of the forests in order to enhance sources for life and use of woods. Cutting plant is not bad however cutting it permanently is bad. If one is cutting plant, he/she should do replanting on the same place or other place. Deforestation is one for many purposes like harvesting, livestock, logging, building houses, furniture, roads, firewood, industrialization, and other many purposes. Deforestation is affecting the environment more badly and more rapidly. Earth was full of forests in the last century however currently around eighty percent of the forests have been cut and destroyed and even rain forests has been disappeared permanently.

Forests are required for the wellness of the wild animals, human being and environment. Because of the deforestation many unique species of the plants and animals has been extinct permanently. The process of plant cutting is disrupting the natural carbon cycle and increasing its level in the environment day by day. Forests are the best medium to utilize the CO2 gas from the environment as well as remove other pollutants from the atmosphere and thus maintain the freshness of the environment. Whenever trees are destroyed or burned by any means it releases carbon and methane which is dangerous for human life. Both of the gases are called as the green house gas and involve in the greenhouse effect which ultimately causes global warming.

Forests are very necessary for the proper rain, getting medicine, air freshness, removing air pollution, getting wood for many purposes, etc. When we cut plants, it disturbs all the cycles and affects human lives. Instead of cutting plants to fulfill the need of paper, we should make the habit of recycling the old things as possible as to avoid the cut of new plants. Just imagine the planet without water, life is not possible. And same way, life is also not possible without plants and forests as they are the source of rain, fresh air, animal habitat, shadows, wood, etc.

Without plant, it is not possible to rain on the earth, nor fresh air, no animals, no shadows, no woods, and medicine. Everywhere would be only heat, warm, drought, flood, storm, carbon dioxide gas, methane, other poisonous gases, no winter season and rainy season, only summer season. We should join our hands together to prevent the deforestation. We should not waste the papers and avoid the unnecessary use of things like paper kitchen towels, facial tissues, etc. We should think about the reuse and recycle of the papers things without wasting them to lessen the need of plants cutting. Saving forests and plants is in our own hand and only a small step from the end of us all may show a big result towards stopping deforestation.

 