                                                                          HINDUISM
Hinduism is the world’s oldest organized religion existing for 4500 years. Based on the prehistoric Vedic text, it is a faith in constant change. Populated by an infinite amount of gods, the belief system is open to adopting any of the gods produced by younger religions. Reincarnation and Karma are the primary mechanisms of Hinduism. The Hindu religion also consists of a belief that man has seven principles; these principles consist of the Dense Physical Body, the Etheric Double, Prana, The Desire Body, Manas, Atma, and Finally Buddhi.

The focal point of this paper is to understand the true nature of Hinduism. To ascertain the true nature of Hinduism it is important to focus on the religion, cultural and societal influences and compare them to its origins. Furthermore, the Hindu desire for liberation from earthly existence would also be explained. As a background of Hinduism as a religion it should be mentioned that it lacks a uniting belief system. In other words, Hinduism is actually many beliefs and practices labeled as a single religion.

Thus it can well be enumerated that Hinduism is more of a compilation of different conflicting school of thoughts unlike more modern traditional religions like Christianity or Islam. Hinduism can be compared to sociological or artistic theories like expressionism or surrealism or for that matter modernism or post modernism and not any religion. The basic of Hinduism is based on six parallel theories, the Shadadarshan or the ‘Six Philosophies’. These are Shyankhya, Yog, Patanjjal, Dbytabad, Adbytabad and Mimansa. (Kar, 2006) Out of these six only two believe in the existence or the need of existence of God.

Furthermore, the saints of Hinduism never referred to these philosophies as religion. Rather they called it Dharma- the way of life or how a life should be led. Dharma is basically a code of conduct for citizen more in the pattern of Capitalism or Communism. Thus in traditional sense the idea of Hinduism is more about philosophy than religion. It is the members of non Hindu origins who labeled it as a religion as it was difficult for them to classify these philosophies as way of life devoid of any religious canon.

To find the true nature of Hinduism it is more relevant t look into the sociological and cultural aspect of India. To could be mentioned in this context that the Indian subcontinent is the only region in the world where we could find almost a billion people living a life where that life is directed by cannons of philosophies and that too without any compulsions or force applied. It is here we find people devoting an entire life to a specific philosophy and maintaining a day to day peaceful existence in close vicinity with its conflicting counterpart or ever a completely different religion like Islam or Christianity.